### ISSUE TITLE
[dns] Add weavedns status to `weave status`

### ISSUE THREAD

**Issue by bboreham** [zettio/weave#237]
The `weave status` command could at minimum state whether weavedns is running.
Perhaps give some other info like how many addresses are known to the local server.

**Comment by rade** [comment]
> (For the synchronisation used in #200 we can use `-X HEAD` so it doesn't bother generating status info)

...which, unfortunately (and per the curl docs), doesn't work. One needs to use `-I` instead. Which breaks our abstraction in the weave script. *grrr*

**Comment by rade** [comment]
@squaremo have you done any work on this or was the [above comment](https://github.com/zettio/weave/issues/237#issuecomment-64598942) just a mock-up?

The output should contain the version in the first line; just as happens for the router.

**Comment by squaremo** [comment]
> have you done any work on this or was the above comment just a mock-up?

It's a mock up, intended to stimulate discussion of what else could appear there.

**Comment by rade** [comment]
We could display all (local, for now) records. After all, the router status shows all MACs in active use, which should be the same order of magnitude of information.

That would take care of #266.

**Comment by inercia** [comment]
I would keep it simple and, for a `GET /status`, I would return just the version, and then I would return all names with a `GET /name`. I was planning to add a full RESTful interface for names anyway, with a `GET` method for listing all IPs for a name, and a `POST` method for adding more IPs...
