### ISSUE TITLE
[dns] list entries

### ISSUE THREAD

**Issue by rade** [zettio/weave#266]
It would be rather handy - mostly for debugging - to be able to list DNS entries.

[AXFR](http://tools.ietf.org/html/rfc5936) is the way to do that and is supported by a bunch of command line tools, e.g. `host -l <domain>` and `dig <domain> axfr`.

The main question we need to answer is to what degree we should control access to this information. Should containers be able to list DNS entries, or just admins? If it's containers, should they be able to list all entries or only entries for domains for which they themselves have an entry?

IMO the answer to the latter is 'all'; containers can already query DNS regardless of whether they themselves have an entry.

There is an obvious information leak here: containers in one app domain can discover the existence of other containers. They can't talk to them, but the names and their existence may constitute sensitive information.

**Comment by awh** [comment]
Can this be closed now?

**Comment by awh** [comment]
Closed by #465.
