### ISSUE TITLE
"Cannot open network namespace" error when running weave from systemd unit on CentOS 7

### ISSUE THREAD

**Issue by errordeveloper** [zettio/weave#293]
This was initially spotted by @yaronr.

Running `sudo weave launch` from CLI manually works, but when trying to run it from a systemd unit (like one shown below), the container fails to start and error displayed is about `eth0` missing.

```
# /etc/systemd/system/weave.service 
[Unit]
Description=Weave Network
Documentation=http://zettio.github.io/weave/
Requires=docker.service
After=docker.service
[Service]
ExecStartPre=/usr/bin/weave launch -password 122333
ExecStartPre=/usr/bin/weave launch-dns 10.10.2.1/16
ExecStart=/usr/bin/docker logs -f weave
SuccessExitStatus=2
ExecStop=/usr/bin/weave stop
ExecStop=/usr/bin/weave stop-dns
```
With a slight modification to the weave script adding call to `ip netns exec $NETNS ip link show eth0` without redirect above  line [215](https://github.com/zettio/weave/blob/34db7044e43e1dfd46c4eca9e242c319f77e246e/weave#L215); you can see the real error message:
```
Cannot open network namespace "2524": Permission denied
```

Firstly, I think we shouldn't hide what's happening there, i.e. capture output and display it on error or something like that...

Secondly, the cause of this might be with systemd+selinux, I'm not too sure.

**Comment by errordeveloper** [comment]
@yaronr FYI, this is not an issue on Fedora 21 Base, not yet on Atomic. I have tested with official images for Base (`ami-66c76c11` @ `eu-west-1`). I have ran `yum upgrade && reboot` prior to testing it, which installed latest  `selinux-policy-3.13.1-103.fc21`.

**Comment by rade** [comment]
#310 will document how to get around this issue.

There is nothing else to do here. -> closing.

**Comment by wanghailiangx** [comment]
Maybe you could try to run "ip netns add 2524" at first.
