### ISSUE TITLE
separate command to download required docker images

### ISSUE THREAD

**Issue by rade** [zettio/weave#308]
Right now a typical installation of weave downloads the required images from the docker hub when they are needed, e.g. the weave image on `weave launch` and weavedns on `weave launch-dns`.

This is convenient but also

- makes execution time of these commands unpredictable
- requires internet connectivity during normal weave operation
- does not download the 'latest' images if there are already images wit that tag present

We can address these issues by introducing a new command, say `weave fetch`, that runs a `docker pull` for all the required images.

@errordeveloper @squaremo thoughts?

**Comment by rade** [comment]
@errordeveloper @squaremo ping

**Comment by squaremo** [comment]
I agree with the rationale, I think it needs a better name. If it's ever likely to do anything other than pull down images, perhaps `weave setup`; otherwise, `weave pull`. It should be made clear that it's not necessary to do it, just a convenience in some scenarios.

**Comment by errordeveloper** [comment]
I also agree with the rationale. I would propose a more specific name, such as `pull-images`. All current sub-commands are mainly to do with the state of the router or the network, this sub-command would be to do with images instead, it thereby should be clearer to distinguish. I would also propose more renaming along this line, e.g. `launch-router`, `stop-router` etc.

**Comment by rade** [comment]
> `weave setup`

I like that. And yes, it might do more than pull images at some point. In fact it could do so even now, e.g. it could create the weave bridge. But lets not do that.

> `weave pull-images`

This rather pushes images into your face. The less the images show up in the weave interface the better; they are an implementation detail.

> `launch-router`

Per the [1.0 walkthrough](#242), dns will be launched as part of `weave launch`, and `weave launch-dns` will be removed. So changing the former to `weave launch-router` now does nothing but annoy our existing users (since every single script they have will break), twice.
