### ISSUE TITLE
[dns] failed lookups not logged intelligibly at default log level

### ISSUE THREAD

**Issue by errordeveloper** [zettio/weave#311]
With `-debug` I can see this:
```
INFO: 2015/01/02 19:09:41.729556 Adding spark-worker-1.weave.local. -> 10.10.1.11
DEBUG: 2015/01/02 19:09:42.404113 Local query: {Name:spark-worker-1.weave.local. Qtype:1 Qclass:1}
DEBUG: 2015/01/02 19:09:42.404158 Local query: {Name:spark-worker-1.weave.local. Qtype:28 Qclass:1}
WARNING: 2015/01/02 19:09:42.404161 Local query not handled: {Name:spark-worker-1.weave.local. Qtype:28 Qclass:1}
DEBUG: 2015/01/02 19:09:42.407608 Local rdns query: {Name:11.1.10.10.in-addr.arpa. Qtype:12 Qclass:1}
DEBUG: 2015/01/02 19:09:42.407619 Looking for address: [10 10 1 11]
DEBUG: 2015/01/02 19:09:42.407623 Found name: spark-worker-1.weave.local.
DEBUG: 2015/01/02 19:09:43.689734 Local rdns query: {Name:0.0.0.0.in-addr.arpa. Qtype:12 Qclass:1}
DEBUG: 2015/01/02 19:09:43.689734 Looking for address: [0 0 0 0]
DEBUG: 2015/01/02 19:09:43.689734 Failed lookup for 0.0.0.0.in-addr.arpa.; sending mDNS query
DEBUG: 2015/01/02 19:09:48.692856 Local rdns query: {Name:0.0.0.0.in-addr.arpa. Qtype:12 Qclass:1}
DEBUG: 2015/01/02 19:09:48.692896 Looking for address: [0 0 0 0]
DEBUG: 2015/01/02 19:09:48.692903 Failed lookup for 0.0.0.0.in-addr.arpa.; sending mDNS query
DEBUG: 2015/01/02 19:09:53.844650 Local query: {Name:spark-masterz.weave.local. Qtype:1 Qclass:1}
DEBUG: 2015/01/02 19:09:53.844650 Failed lookup for spark-masterz.weave.local.; sending mDNS query
DEBUG: 2015/01/02 19:09:53.844650 Local query: {Name:spark-masterz.weave.local. Qtype:28 Qclass:1}
WARNING: 2015/01/02 19:09:53.844650 Local query not handled: {Name:spark-masterz.weave.local. Qtype:28 Qclass:1}
WARNING: 2015/01/02 19:09:54.346368 Local query not handled: {Name:spark-masterz.weave.local.weave.local. Qtype:28 Qclass:1}
DEBUG: 2015/01/02 19:09:54.346326 Local query: {Name:spark-masterz.weave.local.weave.local. Qtype:1 Qclass:1}
DEBUG: 2015/01/02 19:09:54.346345 Failed lookup for spark-masterz.weave.local.weave.local.; sending mDNS query
DEBUG: 2015/01/02 19:09:54.346363 Local query: {Name:spark-masterz.weave.local.weave.local. Qtype:28 Qclass:1}
```

And without:
```
INFO: 2015/01/02 19:09:41.729556 Adding spark-worker-1.weave.local. -> 10.10.1.11
WARNING: 2015/01/02 19:09:42.404161 Local query not handled: {Name:spark-worker-1.weave.local. Qtype:28 Qclass:1}
WARNING: 2015/01/02 19:09:53.844650 Local query not handled: {Name:spark-masterz.weave.local. Qtype:28 Qclass:1}
WARNING: 2015/01/02 19:09:54.346368 Local query not handled: {Name:spark-masterz.weave.local.weave.local. Qtype:28 Qclass:1}
```

The messages with `Local query not handled` are not as meaningful as `Failed lookup for spark-masterz.weave.local.weave.local.; sending mDNS query`.

The `Qtype:28` is a separate issue, it somehow seems to look for an `AAAA` record, but that's probably to do with Java. Anyhow, the record in question in question doesn't exists, but instead we show an obscure `Local query not handled` message.

**Comment by rade** [comment]
@squaremo @bboreham

**Comment by bboreham** [comment]
The thing is, until we've sent the mDNS query qnd waited for a response, we don't know the name doesn't exist.  So the "failed lookup" messages are correctly debug-only. 

I think you're asking for a warning if the mDNS query doesn't find anything. Which we can try, I guess. 

Warning when we get a query that it isn't coded to handle seems right to me. Yes, it's obscure, but that's why it's there - so we can learn what real systems do that we didn't expect.

**Comment by squaremo** [comment]
Q:
> Anyhow, the record in question in question doesn't exists, but instead we show an obscure Local query not handled message.

A:
> Warning when we get a query that it isn't coded to handle seems right to me.

We might also put in why it wasn't handled.

> I think you're asking for a warning if the mDNS query doesn't find anything. Which we can try, I guess.

Yar, it sounds like it would be helpful if weaveDNS warned when it couldn't answer a query.

**Comment by rade** [comment]
Technically failed lookups are "normal operation" for DNS. However, they are rather more interesting for troubleshooting than what most people would consider 'debug' information. So they should be logged at a higher level. @squaremo and I reckon it should be 'INFO'.

See also #329.

There are a few other log messages that ought to be tweaked:

- we log a "query not handled" warning when getting anything other than a TypeA query on weave.local. But really we *do* handle those queries; it's just that our zone contains no matching records. So I think we should log this as a "no records for query" info message instead.

- we log a "Reverse query not handled" warning when getting anything other than PTR query for reverse lookups. By the same logic as above, we actually do handle those queries. However, here we really do not expect to see such queries, so logging a "unexpected reverse query" warning seems most appropriate.
