### ISSUE TITLE
Point-in-time / versioning?

### ISSUE THREAD

**Issue by lvangool** [zettio/weave#315]
One question about stability. Right now we deploy a point-in-time copy of the weave script (to protect against breaking changes). However, we recently found that an incompatibility with our copy and the image itself resulted in a break (the weave container didn't start).

So to protect against this we can either:
a) Take a point-in-time copy and store our own script AND image - which we update as-and-when necessary
b) Rely on your own repository directly - as long as you don't introduce breaking changes.

What is your suggested approach to this? I've seen a couple of things regarding versioning support; when would that be available and would that be a better approach?

Thanks - and keep up the great work!

**Comment by rade** [comment]
Did you see the versioning-related items in the recent weave releases? https://github.com/zettio/weave/blob/master/CHANGELOG.md. The issues you describe should be addressed by those.

**Comment by lvangool** [comment]
Great! One thing though, even if I install v0.7.0 via: 
https://github.com/zettio/weave/releases/download/v0.7.0/weave

it ends up starting the container "zettio/weave:0.8.0"
(Which is essentially the issue I had originally, albeit for an older script)

Is this an artefact of switching on the versioning (and not likely to be an issue going forward) or is this always going to be the case (ie. just pulling the 'latest' docker image always)

**Comment by rade** [comment]
> even if I install v0.7.0 it ends up starting v0.8.0

That is because, as per the change log, the script/image version alignment only happened in 0.8.0.

**Comment by lvangool** [comment]
Got it! Updating on our side - thanks again.
