### ISSUE TITLE
How weave's application isolation works?

### ISSUE THREAD

**Issue by mingqi** [zettio/weave#316]
I read through weave's [how it works](http://zettio.github.io/weave/how-it-works.html) document. If my understanding correct, weave router is works on L2 networking. Weave's application isolation is IP subnet isolation which is L3. I'm cursor that how weave implement it?  I found another question #84 about isolation, but I didn't get answer from  it.

**Comment by rade** [comment]
Weave application containers get an `ethwe` interface with the IP address and subnet specified in `weave run`, and associated routing table entries. Containers cannot modify their interface settings or routing tables, and therefore the only IP addresses reachable through ethwe are those in the same subnet.

Circumventing that would require packet capture/injection. Which can be prevented with `--cap-drop net_raw`.

**Comment by mingqi** [comment]
@rade thank for your explanation. That's clear. I have another question: does weave provide any approach to change the Weave default behaviour, e.g. I want to disable isolation for specified two subnet,  make them connectable each other. I think it can be done  by changing the container's route table. I read through the script [weave](https://github.com/zettio/weave/blob/master/weave) but didn't find out codes setting the route table. is Docker's behaviour to setup route table in 'docker run' or weave? thanks

**Comment by rade** [comment]
>  I want to disable isolation for specified two subnet, make them connectable each other.

Weave supports this by allowing containers to have [IP addresses on multiple subnets](http://zettio.github.io/weave/features.html#dynamic-network-attachment).

> I think it can be done by changing the container's route table.

That is the other way to do this, but not something we've tried. And it cannot be accomplished from *inside* a container with normal capabilities; you'd need CAP_NET_ADMIN, I think, which is not something you'd want to grant to a container in general.

btw, just to follow up on the app isolation discussion...one extra element to the puzzle is [reverse path filtering](http://tldp.org/HOWTO/Adv-Routing-HOWTO/lartc.kernel.rpf.html), which is enabled by default (and cannot be disabled in a container with standard capabilities), and, amongst other things, prevents broadcast packets from "foreign" subnets from reaching a container.

**Comment by mingqi** [comment]
thank your answer, @rade , closing this issue.
