### ISSUE TITLE
[dns] handle all query types

### ISSUE THREAD

**Issue by rade** [zettio/weave#318]
weavedns currently only handles A and AAAA queries. That is enough for most apps but not all, which is one reason preventing is from configuring container name resolution via weavedns by default.

So we should improve our nameserver implementation to handle all query types.

This in turn requires a departure from the current model where we handle A/AAAA queries by a simple lookup with `net.LookupIP`, since that won't work for any other query types. Instead we need to do proper query forwarding. Which [isn't hard](https://github.com/kenshinx/godns/blob/a3f7507c4a853ea9021ce596005831b668808d3b/resolver.go#L24) but requires that we figure out what nameserver to talk to. Ideally we'd read resolv.conf. Which [go has code for](https://golang.org/src/net/dnsconfig_unix.go?h=dnsReadConfig#L23) but annoyingly hides behind higher level APIs that are of no use to us.

**Comment by bboreham** [comment]
More code to read resolv.conf [here](https://github.com/miekg/dns/blob/master/clientconfig.go#L22)

**Comment by squaremo** [comment]
https://github.com/squaremo/weave/compare/zettio:master...squaremo:issue318_proxy_all_dns?expand=1

**Comment by squaremo** [comment]
Reverse lookups are a problem: if we don't have the address locally, how do we know whether to ask our peers or to ask the internet? (weaveDNS doesn't presently attempt anything beyond checking the local zone database).

A not-completely-terrible solution might be to ask mDNS, and only ask the internet after it has timed out. A refinement of that might be to have an heuristic for which order to ask {internet, mDNS}, based on which addresses are in the DB. I'd have to think about how this affects correctness.

**Comment by rade** [comment]
> A not-completely-terrible solution might be to ask mDNS, and only ask the internet after it has timed out.

Good enough for now, I think.

**Comment by bboreham** [comment]
Closed because the bulk of this issue is done; remainder in new issue at #346
