### ISSUE TITLE
trips over spaces in `docker inspect --format="TEMPLATE"`

### ISSUE THREAD

**Issue by errordeveloper** [zettio/weave#319]
We have seen reoccurrence of docker/docker#8792 on Ubuntu Core. It's unclear why this normally works, however the examples shown documentation for [text/template](http://golang.org/pkg/text/template/) package do not contain spaces.

**Comment by rade** [comment]
I found a [whitespace change to the go text/template lexer](https://github.com/golang/go/commit/de13e8dccdc9acccf55ebc1b306a0e83b08d8704), but that was ages ago and, afaict, appeared in go 1.1

**Comment by errordeveloper** [comment]
Well, it turns out that this is really a bug in Snappy's docker wrapper.

```
root@localhost:~# docker inspect --format='{{ .NetworkSettings }}' weave
Template parsing error: template: :1: unexpected unclosed action in command
INFO[0000] Template parsing error: template: :1: unexpected unclosed action in command 
root@localhost:~# cat `which docker`
#!/bin/sh
##TARGET=/apps/docker/1.3.2.007/bin/docker
#TMPDIR=/run/apps/docker
cd /apps/docker/1.3.2.007
aa-exec -p docker_docker_1.3.2.007 -- /apps/docker/1.3.2.007/bin/docker $@
root@localhost:~# /apps/docker/1.3.2.007/bin/docker inspect --format='{{ .NetworkSettings }}' weave
map[Bridge:docker0 Gateway:172.17.42.1 IPAddress:172.17.0.2 IPPrefixLen:16 MacAddress:02:42:ac:11:00:02 PortMapping:<nil> Ports:map[6783/tcp:[map[HostIp:0.0.0.0 HostPort:6783]] 6783/udp:[map[HostIp:0.0.0.0 HostPort:6783]]]]
root@localhost:~# 
```

**Comment by rade** [comment]
missing " around the $@?

**Comment by errordeveloper** [comment]
On Wed Jan 07 2015 at 3:42:59 PM rade <notifications@github.com> wrote:

> missing " around the $@?
>
Exactly...
