### ISSUE TITLE
Not getting weave-dns to work across instances (AWS)

### ISSUE THREAD

**Issue by tcolar** [zettio/weave#322]
After seeing DNS not working properly in my large complex setup I decided to start simple and try the ping test as explained here:
https://github.com/zettio/weave/tree/master/weavedns  

I have two AWS instances and they use a security group that allows UDP and TCP on port 6783, anything else needs to be opened, is the DNS encapsulated through there as well ??

The ubuntu container in each instance are able to ping themselves but not the opposite container.

Here is a bit of data, let me know if anything else would be useful, I'm not sure exactly how to debug this. 

Thanks

----------
cat /etc/resolv.conf 
nameserver 172.17.42.1

------------
route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         172.17.42.1     0.0.0.0         UG    0      0        0 eth0
10.1.1.0        0.0.0.0         255.255.255.0   U     0      0        0 ethwe
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 eth0
224.0.0.0       0.0.0.0         240.0.0.0       U     0      0        0 ethwe

------------- 
    weave container
docker logs ab93b99d9e04
weave 2015/01/07 03:46:17.140533 Command line options: map[iface:ethwe name:7a:5b:96:12:62:86 wait:5]
weave 2015/01/07 03:46:17.140661 Command line peers: []
weave 2015/01/07 03:46:18.141374 Communication between peers is unencrypted.
weave 2015/01/07 03:46:18.141919 Our name is 7a:5b:96:12:62:86
weave 2015/01/07 03:46:18.167372 Sniffing traffic on &{9 65535 ethwe 6e:5f:da:1f:f3:c9 up|broadcast|multicast}
weave 2015/01/07 03:46:18.167435 Discovered our MAC 6e:5f:da:1f:f3:c9
weave 2015/01/07 03:46:18.615262 Discovered local MAC c6:68:a7:71:19:b2
weave 2015/01/07 03:46:18.851026 Discovered local MAC 7a:5b:96:12:62:86
weave 2015/01/07 03:46:41.094946 Discovered local MAC 6e:01:81:3d:87:a7
weave 2015/01/07 03:47:34.592266 Peer 7a:5b:96:12:62:86 established active connection to remote peer 7a:ff:a9:6b:4b:46 at 54.149.63.156:59984
weave 2015/01/07 03:47:34.592586 EMSGSIZE on send, expecting PMTU update (IP packet was 60042 bytes, payload was 60034 bytes)
weave 2015/01/07 03:47:34.592613 ->[7a:ff:a9:6b:4b:46]: Effective PMTU set to 8939
weave 2015/01/07 03:47:34.602808 EMSGSIZE on send, expecting PMTU update (IP packet was 8981 bytes, payload was 8973 bytes)
weave 2015/01/07 03:47:34.602831 ->[7a:ff:a9:6b:4b:46]: Effective PMTU set to 1438
weave 2015/01/07 03:47:34.603735 ->[7a:ff:a9:6b:4b:46]: Effective PMTU verified at 1438
weave 2015/01/07 03:47:35.545209 Discovered remote MAC ba:e5:03:b4:cf:f7 at 7a:ff:a9:6b:4b:46
weave 2015/01/07 03:48:37.423007 Discovered local MAC c2:d5:e0:fe:39:7b
weave 2015/01/07 03:48:46.125410 Discovered remote MAC 96:77:18:7a:cc:d8 at 7a:ff:a9:6b:4b:46
weave 2015/01/07 03:49:21.310966 Discovered local MAC ee:e7:32:52:de:ca
weave 2015/01/07 03:50:47.513220 Discovered remote MAC 1e:0c:0d:7e:43:c6 at 7a:ff:a9:6b:4b:46
weave 2015/01/07 03:56:15.628748 Discovered remote MAC 5a:16:0d:c5:88:db at 7a:ff:a9:6b:4b:46
weave 2015/01/07 03:57:18.145165 Expired MAC 6e:5f:da:1f:f3:c9 at 7a:5b:96:12:62:86
weave 2015/01/07 03:57:18.145197 Expired MAC c6:68:a7:71:19:b2 at 7a:5b:96:12:62:86
weave 2015/01/07 03:57:18.145204 Expired MAC 7a:5b:96:12:62:86 at 7a:5b:96:12:62:86
weave 2015/01/07 03:57:18.145212 Expired MAC 6e:01:81:3d:87:a7 at 7a:5b:96:12:62:86
weave 2015/01/07 03:57:57.832513 ->[7a:ff:a9:6b:4b:46]: error: read tcp4 54.149.63.156:59984: connection reset by peer
weave 2015/01/07 03:57:57.832562 ->[7a:ff:a9:6b:4b:46]: connection shutting down
weave 2015/01/07 03:57:57.832706 Removing unreachable Peer 7a:ff:a9:6b:4b:46 (v1) (UID 4423709205630578981)
weave 2015/01/07 03:58:52.018469 Peer 7a:5b:96:12:62:86 established active connection to remote peer 7a:ff:a9:6b:4b:46 at 54.149.63.156:53998
weave 2015/01/07 03:58:52.020982 EMSGSIZE on send, expecting PMTU update (IP packet was 60042 bytes, payload was 60034 bytes)
weave 2015/01/07 03:58:52.021011 ->[7a:ff:a9:6b:4b:46]: Effective PMTU set to 8939
weave 2015/01/07 03:58:52.031234 EMSGSIZE on send, expecting PMTU update (IP packet was 8981 bytes, payload was 8973 bytes)
weave 2015/01/07 03:58:52.031257 ->[7a:ff:a9:6b:4b:46]: Effective PMTU set to 1438
weave 2015/01/07 03:58:52.032158 ->[7a:ff:a9:6b:4b:46]: Effective PMTU verified at 1438
weave 2015/01/07 03:58:52.756862 Discovered remote MAC 9a:a5:af:bd:40:ca at 7a:ff:a9:6b:4b:46
weave 2015/01/07 03:59:18.145712 Expired MAC c2:d5:e0:fe:39:7b at 7a:5b:96:12:62:86
weave 2015/01/07 03:59:26.552597 Discovered remote MAC f2:6d:24:40:84:7a at 7a:ff:a9:6b:4b:46
weave 2015/01/07 03:59:40.416634 Discovered remote MAC 36:98:48:86:c8:74 at 7a:ff:a9:6b:4b:46
weave 2015/01/07 04:00:18.146106 Expired MAC ee:e7:32:52:de:ca at 7a:5b:96:12:62:86
weave 2015/01/07 04:01:32.278998 Discovered local MAC 36:83:f3:5c:40:7b
weave 2015/01/07 04:03:25.943009 Discovered local MAC da:8e:49:2c:dd:52
weave 2015/01/07 04:03:43.528630 Discovered local MAC c2:d5:e0:fe:39:7b
weave 2015/01/07 04:09:18.176754 Expired MAC 9a:a5:af:bd:40:ca at 7a:ff:a9:6b:4b:46

----------- 
    weave dns container  (plume is this host name, the other is petra)
docker logs a9a01b49c9dd
INFO: 2015/01/07 03:48:37.139557 Using Docker API on unix:///var/run/docker.sock: &[KernelVersion=3.13.0-36-generic Os=linux Version=1.3.1 ApiVersion=1.15 Arch=amd64 GitCommit=4e9bbfa GoVersion=go1.3.3]
INFO: 2015/01/07 03:48:37.139686 Waiting for interface ethwe to come up
INFO: 2015/01/07 03:48:37.288867 Container 9d7003fc6a9b694671772db1954ae4fdecab2fcf6924ea4bd6fa1a6dfa7da951 down. Removing records
INFO: 2015/01/07 03:48:38.140064 Interface ethwe is up
INFO: 2015/01/07 03:48:38.140153 Using mDNS on ethwe
INFO: 2015/01/07 03:48:38.140356 Listening for DNS on :53
INFO: 2015/01/07 03:48:38.574288 Ignoring name a9a01b49c9dd.., not in weave.local.
INFO: 2015/01/07 03:48:38.638582 Ignoring name 2539aecae4d2.., not in weave.local.
INFO: 2015/01/07 03:49:21.181063 Container de30ce44465dbdee48082a91f89f3dcc2ecf6ae24b0a052cf54b5340fc6607cc down. Removing records
INFO: 2015/01/07 03:49:21.444528 Adding plume.weave.local. -> 10.1.1.25
INFO: 2015/01/07 04:00:52.661227 Container 8ff8f6a06757c4b88886d368430b04d47fb26e07984c886810affb0aada2a053 down. Removing records
INFO: 2015/01/07 04:01:32.145000 Container 22098c3d9434687eec675e51049b39eee71452da5193ae9fe6dacb1ffe69b5b1 down. Removing records
INFO: 2015/01/07 04:01:32.409117 Adding plume.weave.local. -> 10.1.1.25
INFO: 2015/01/07 04:03:13.185401 Container 6576cbcc67ba2683d11677e0ce5eb2ef7033f24c2f5b116139c584f3c398d3b6 down. Removing records
INFO: 2015/01/07 04:03:25.812963 Container 1c59b6b5ed60f0cf19e0bb73018768777bb9c9faccebdd4eef61b32b8eecf8e6 down. Removing records
INFO: 2015/01/07 04:03:26.059721 Adding plume.weave.local. -> 10.1.1.25
INFO: 2015/01/07 04:10:00.030356 Container a6718a886f4ea428eabd40f73bb771639cb2663bb3bfd5d46398d4c60b370006 down. Removing records

---------
iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     udp  --  anywhere             ip-172-17-0-8.us-west-2.compute.internal  udp dpt:domain
ACCEPT     udp  --  anywhere             ip-172-17-0-7.us-west-2.compute.internal  udp dpt:6783
ACCEPT     tcp  --  anywhere             ip-172-17-0-7.us-west-2.compute.internal  tcp dpt:6783
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

**Comment by tcolar** [comment]
BTW, if there is better channel to discuss this, lmk.

**Comment by bboreham** [comment]
>  is the DNS encapsulated through there as well

Yes, weave-dns operates over the weave network, so it doesn't need any further ports opened.

> how to debug this

A ping test is an excellent start, as is looking in the weave logs.  Let's see:

    weave 2015/01/07 03:47:34.592266 Peer 7a:5b:96:12:62:86 established active connection to remote peer 7a:ff:a9:6b:4b:46 at 54.149.63.156:59984

Good - we need the weave processes (the 'peers') to connect to each other.  The messages about PMTU all look normal.

    weave 2015/01/07 03:57:57.832513 ->[7a:ff:a9:6b:4b:46]: error: read tcp4 54.149.63.156:59984: connection reset by peer

Did you stop the other process?  This is 10 minutes later, so let's assume so.

Unfortunately, I don't have enough information to understand the full problem.  Suggestions:

1. Do a ping test using the IP addresses of containers, to check the overlay network works before adding DNS.
2. Ping the IP address of the DNS containers (first one is 10.1.254.1 in the example)
3. Show the output of `weave ps` on each host

> BTW, if there is better channel to discuss this, lmk.

Here is fine; we also have [email and IRC channels](https://github.com/zettio/weave#contact-us)

**Comment by tcolar** [comment]
Ping works: (so weave networking is good)

On each instance i'm able to resolve all the local host containers so weave-dns appears to work, EXCEPT the dns names do not appear on the other host. So it seems the weave-dns on each servers are not talking to each other.

-----
root@etra ping 10.1.1.26
PING 10.1.1.26 (10.1.1.26) 56(84) bytes of data.
64 bytes from 10.1.1.26: icmp_seq=1 ttl=64 time=0.037 ms

root@petra:/# ping 10.1.1.25
PING 10.1.1.25 (10.1.1.25) 56(84) bytes of data.
64 bytes from 10.1.1.25: icmp_seq=1 ttl=64 time=17.3 ms

------
Should I be able to ping/dig the dns server ?
I can't ping  ping 10.1.251.1 and there are no routes for it.
------
What should dig sho as the dns server ?

dig petra            

; <<>> DiG 9.9.5-3-Ubuntu <<>> petra
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 19078
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;petra.				IN	A

;; Query time: 1 msec
;; SERVER: 172.17.42.1#53(172.17.42.1)
;; WHEN: Wed Jan 07 17:57:27 UTC 2015
;; MSG SIZE  rcvd: 23

----
INFO: 2015/01/07 18:24:55.616138 Using Docker API on unix:///var/run/docker.sock: &[Os=linux Version=1.3.1 ApiVersion=1.15 Arch=amd64 GitCommit=4e9bbfa GoVersion=go1.3.3 KernelVersion=3.13.0-36-generic]
INFO: 2015/01/07 18:24:55.616239 Waiting for interface ethwe to come up
INFO: 2015/01/07 18:24:56.616631 Interface ethwe is up
INFO: 2015/01/07 18:24:56.616727 Using mDNS on ethwe
INFO: 2015/01/07 18:24:56.616966 Listening for DNS on :53
INFO: 2015/01/07 18:24:57.082867 Ignoring name 5eea15a8899b.., not in weave.local.
INFO: 2015/01/07 18:24:57.210508 Adding petra4.weave.local. -> 10.1.1.34
INFO: 2015/01/07 18:24:57.270357 Adding petra2.weave.local. -> 10.1.1.30
INFO: 2015/01/07 18:24:57.334270 Adding petra.weave.local. -> 10.1.1.28
INFO: 2015/01/07 18:24:57.402382 Ignoring name 2539aecae4d2.., not in weave.local.
INFO: 2015/01/07 18:25:58.606077 Adding petra5.weave.local. -> 10.1.1.35

---
INFO: 2015/01/07 18:24:31.738682 Using Docker API on unix:///var/run/docker.sock: &[Arch=amd64 GitCommit=4e9bbfa GoVersion=go1.3.3 KernelVersion=3.13.0-36-generic Os=linux Version=1.3.1 ApiVersion=1.15]
INFO: 2015/01/07 18:24:31.738801 Waiting for interface ethwe to come up
INFO: 2015/01/07 18:24:31.890534 Container 10407e6d4fea4515514d873afdc5347ee032deb1d03d0a71e84c0f147c8e96ba down. Removing records
INFO: 2015/01/07 18:24:32.739352 Interface ethwe is up
INFO: 2015/01/07 18:24:32.739442 Using mDNS on ethwe
INFO: 2015/01/07 18:24:32.739693 Listening for DNS on :53
INFO: 2015/01/07 18:24:33.180080 Ignoring name 9003dd01e325.., not in weave.local.
INFO: 2015/01/07 18:24:33.308034 Adding plume.weave.local. -> 10.1.1.25
INFO: 2015/01/07 18:24:33.388379 Adding plume2.weave.local. -> 10.1.1.26

**Comment by rade** [comment]
How did you invoke `launch-dns` on the machines? i.e. what IP/subnet did you supply?

And, as @bboreham suggested, please post the output of `weave ps` on each host.

> Should I be able to ping/dig the dns server ?

No.

**Comment by tcolar** [comment]
Server 1:
./weave launch
./weave launch-dns 10.1.254.1/24
./weave run --with-dns 10.1.1.27/24 -ti -h plume2.weave.local ubuntu

---
Server 2:
./weave launch 172.31.18.99   (note: i've tried with both internal and external AWS IP's)
./weave launch-dns 10.1.254.1/24
./weave run --with-dns 10.1.1.35/24 -ti -h petra5.weave.local ubuntu

----
server 1 weave ps
9003dd01e325 6a:b0:87:51:b7:9a 10.1.254.1/24
6fc13ffa9572 c6:68:71:8e:e0:fd
768435341ae5 62:35:08:0d:b7:2d 10.1.1.25/24
e9e928d35211 e2:db:69:23:e0:84 10.1.1.25/24

---
server 2 weave ps
0eebaa4c31e3 de:92:71:03:4e:77 10.1.1.35/24
5eea15a8899b da:73:49:72:53:e0 10.1.254.1/24
b14e102fdc81 fa:ed:e2:94:dc:43
6f52a9519596 a6:ef:6d:3e:2c:86 10.1.1.34/24
567de527eb0e ea:1a:f2:fd:2f:22 10.1.1.30/24
ed97b4693b0a 92:c2:01:c9:60:c2 10.1.1.28/24
2539aecae4d2 6e:01:81:3d:87:a7 10.0.1.1/24

----
server 1 docker ps
9003dd01e325        zettio/weavedns:0.8.0   "/home/weave/weavedn   14 minutes ago      Up 14 minutes                 172.17.42.1:53->53/udp                           weavedns                
6fc13ffa9572        zettio/weave:0.8.0      "/home/weave/weaver    20 minutes ago      Up 20 minutes                 0.0.0.0:6783->6783/tcp, 0.0.0.0:6783->6783/udp   weave                   
768435341ae5        ubuntu:14.04            "/bin/bash"            50 minutes ago      Up 50 minutes                                                                  determined_nobel        
e9e928d35211        ubuntu:14.04            "/bin/bash"            About an hour ago   Up About an hour                                                               agitated_brown          

----
server 2 docker ps
0eebaa4c31e3        ubuntu:14.04            "/bin/bash"            12 minutes ago      Up 12 minutes                                                                sleepy_wright        
5eea15a8899b        zettio/weavedns:0.8.0   "/home/weave/weavedn   13 minutes ago      Up 13 minutes               172.17.42.1:53->53/udp                           weavedns             
b14e102fdc81        zettio/weave:0.8.0      "/home/weave/weaver    15 minutes ago      Up 15 minutes               0.0.0.0:6783->6783/tcp, 0.0.0.0:6783->6783/udp   weave                
6f52a9519596        ubuntu:14.04            "/bin/bash"            20 minutes ago      Up 20 minutes                                                                cocky_meitner        
567de527eb0e        ubuntu:14.04            "/bin/bash"            34 minutes ago      Up 34 minutes                                                                kickass_carson       
ed97b4693b0a        ubuntu:14.04            "/bin/bash"            40 minutes ago      Up 40 minutes                                                                tender_leakey        
2539aecae4d2        ubuntu:14.04            "/bin/bash"            14 hours ago        Up 14 hours                                                                  naughty_jones        
roo

**Comment by rade** [comment]
You supplied the same IP address to `weave launch-dns` on both machines. As per [the docs](https://github.com/zettio/weave/tree/master/weavedns#using-weavedns)...

> Each weaveDNS container started with `launch-dns` needs to be given its own, unique, IP address

**Comment by tcolar** [comment]
Ha duh, i completely misunderstood that, my bad. 
I used weave launch-dns 10.1.254.1/24 on host2 and It seems to work now.

I would suggest adding the commands host 2 in the Readme example for extra clarity.

Thanks !

**Comment by rade** [comment]
To be fair, we only added that particular wording to the docs earlier today, so I'm not surprised you missed it ;)

**Comment by tcolar** [comment]
Alright that worked.

Now i'm trying to do that within docker:

----
Host1:
docker run -v /var/run/docker.sock:/var/run/docker.sock -v /proc:/hostproc --privileged=true --env PROCFS=/hostproc --net=host igneoussystems/weave:latest launch

docker run -v /var/run/docker.sock:/var/run/docker.sock -v /proc:/hostproc --privileged=true --env PROCFS=/hostproc --net=host igneoussystems/weave:latest launch-dns 10.1.254.1/24
6a715c7ee5bb67c906488d7e0dfd722d794cef05e5095c8be8eb442e0d24779a

docker run -v /var/run/docker.sock:/var/run/docker.sock -v /proc:/hostproc --privileged=true --env PROCFS=/hostproc --net=host igneoussystems/weave:latest run --with-dns 10.1.1.1/24 -ti -h host1-1.weave.local ubuntu

docker run -v /var/run/docker.sock:/var/run/docker.sock -v /proc:/hostproc --privileged=true --env PROCFS=/hostproc --net=host igneoussystems/weave:latest run --with-dns 10.1.1.2/24 -ti -h host1-2.weave.local ubuntu

---
Host2:
docker run -v /var/run/docker.sock:/var/run/docker.sock -v /proc:/hostproc --privileged=true --env PROCFS=/hostproc --net=host igneoussystems/weave:latest launch 172.31.18.98

docker run -v /var/run/docker.sock:/var/run/docker.sock -v /proc:/hostproc --privileged=true --env PROCFS=/hostproc --net=host igneoussystems/weave:latest launch-dns 10.1.254.2/24

docker run -v /var/run/docker.sock:/var/run/docker.sock -v /proc:/hostproc --privileged=true --env PROCFS=/hostproc --net=host igneoussystems/weave:latest run --with-dns 10.1.1.4/24 -ti -h host2-2.weave.local ubuntu

docker run -v /var/run/docker.sock:/var/run/docker.sock -v /proc:/hostproc --privileged=true --env PROCFS=/hostproc --net=host igneoussystems/weave:latest run --with-dns 10.1.1.3/24 -ti -h host2-1.weave.local ubuntu

----
Ok now I attach to host1-1
ping host1-2 (same host) works juts fine

Now ping host2-1(from host1)  is strange:

if i do ping host2-1 It resolves properly but the ping times are very very slow
ping host2-1
64 bytes from 10.1.1.3: icmp_seq=1 ttl=64 time=0.619 ms
64 bytes from 10.1.1.3: icmp_seq=2 ttl=64 time=0.924 ms
64 bytes from 10.1.1.3: icmp_seq=3 ttl=64 time=0.865 ms

If i ping by the IP, it's fast:
ping 10.1.1.3
PING 10.1.1.3 (10.1.1.3) 56(84) bytes of data.
64 bytes from 10.1.1.3: icmp_seq=1 ttl=64 time=1.03 ms
64 bytes from 10.1.1.3: icmp_seq=2 ttl=64 time=0.879 ms
64 bytes from 10.1.1.3: icmp_seq=3 ttl=64 time=1.11 ms

Any idea why that might be ?

**Comment by rade** [comment]
huh? Those ping times are all around 1ms.

**Comment by tcolar** [comment]
you are right, what i'm seeing is:

ping host2-1
PING host2-2.weave.local (10.1.1.3) 56(84) bytes of data.
...... NOTHING for many (5+) seconds
64 bytes from 10.1.1.3: icmp_seq=1 ttl=64 time=0.619 ms

ping 10.1.1.3
PING 10.1.1.3 (10.1.1.3) 56(84) bytes of data.
.... no delay here
64 bytes from 10.1.1.3: icmp_seq=1 ttl=64 time=1.03 ms

**Comment by rade** [comment]
How long does `nslookup host2-1` take?

**Comment by tcolar** [comment]
nslookup of host2-1 failed altogether, it worked with the fqdn 

time nslookup host2-1
Server:		172.17.42.1
Address:	172.17.42.1#53

** server can't find host2-1: NXDOMAIN


real	0m0.008s
user	0m0.007s
sys	0m0.000s
root@host1-2:/# time nslookup host2-1.weave.local
Server:		172.17.42.1
Address:	172.17.42.1#53

Non-authoritative answer:
Name:	host2-1.weave.local
Address: 10.1.1.3


real	0m0.010s
user	0m0.000s
sys	0m0.007s

**Comment by tcolar** [comment]
maybe i should trying using --dns-search ?

**Comment by rade** [comment]
does `ping host2-1.weave.local` produce a result more quickly?

Btw, above you wrote
> ping host2-1
> PING host2-2.weave.local (10.1.1.3) 56(84) bytes of data.

Why does it say "host2-1" in the first line but "host2-2" in the 2nd?

**Comment by tcolar** [comment]
you can ignore the host2-1 vs host2-2 it's just me typing the wrong thing in here.

using the fqdn with ping didn't help

ping host2-1.weave.local
PING host2-1.weave.local (10.1.1.3) 56(84) bytes of data.
.... 7 SECONDS here .....
64 bytes from 10.1.1.3: icmp_seq=1 ttl=64 time=0.552 ms
64 bytes from 10.1.1.3: icmp_seq=2 ttl=64 time=0.887 ms

**Comment by rade** [comment]
> maybe i should trying using --dns-search ?

Can't see how that would make a difference.

> using the fqdn with ping didn't help

ok. time to figure out where the time is going. Run the dns containers with debugging (`weave launch-dns cidr -debug`), then run `docker logs -f weavedns` on both of them, then run the ping and observe whether there is any delay between the ping invocation and the dns containers printing something in their logs. Post the logs and not where, if anywhere, the delay occurred.

**Comment by tcolar** [comment]
ping host1-1
You can see that 5 seconds delay in the weave-dns log:

------
DEBUG: 2015/01/08 03:04:08.511288 Local query: {Name:host1-1.weave.local. Qtype:1 Qclass:1}
DEBUG: 2015/01/08 03:04:08.511328 Failed lookup for host1-1.weave.local.; sending mDNS query
DEBUG: 2015/01/08 03:04:08.513490 Got address response host1-1.weave.local. to query host1-1.weave.local. addr 10.1.1.1
DEBUG: 2015/01/08 03:04:08.516176 Local rdns query: {Name:1.1.1.10.in-addr.arpa. Qtype:12 Qclass:1}
DEBUG: 2015/01/08 03:04:08.516200 Looking for address: [10 1 1 1]
DEBUG: 2015/01/08 03:04:08.516223 Failed lookup for 1.1.1.10.in-addr.arpa.; sending mDNS query
DEBUG: 2015/01/08 03:04:13.516686 Local rdns query: {Name:1.1.1.10.in-addr.arpa. Qtype:12 Qclass:1}
DEBUG: 2015/01/08 03:04:13.516715 Looking for address: [10 1 1 1]
DEBUG: 2015/01/08 03:04:13.516727 Failed lookup for 1.1.1.10.in-addr.arpa.; sending mDNS query
INFO: 2015/01/08 03:04:51.154628 Container 6afb60de76ac531a57ab29997d7f74a19f58f888b60fefcdf148560d3d8c6197 down. Removing records

**Comment by rade** [comment]
ah. it's the reverse lookup that is failing. Try running ping with the `-n` option.

**Comment by tcolar** [comment]
Yea, confirmed taht it's the reverse lookup taking time.

I see you opened #326 so feel free  to close this.

Thanks.
