### ISSUE TITLE
connection attempt rejected due to existing 'phantom' connection

### ISSUE THREAD

**Issue by rade** [zettio/weave#341]
````
weave 2015/01/12 17:33:49.347680 ->[7a:bd:50:f0:88:62]: error: write tcp4 92.222.67.234:55178: connection reset by peer
weave 2015/01/12 17:33:49.347800 ->[7a:bd:50:f0:88:62]: connection shutting down
weave 2015/01/12 17:33:55.928397 ->[92.222.67.234:51429] encountered error during handshake: Already have connection to 7a:bd:50:f0:88:62 at 92.222.67.234:55178
weave 2015/01/12 17:33:58.707130 ->[92.222.67.234:51440] encountered error during handshake: Already have connection to 7a:bd:50:f0:88:62 at 92.222.67.234:55178
(repeated over and over)
````

And the other end...
````
weave 2015/01/12 17:33:55.926016 Attempting connection to 92.222.64.171:6783
weave 2015/01/12 17:33:55.928411 ->[7a:81:57:bc:62:f3]: error: read tcp4 92.222.64.171:6783: connection reset by peer
weave 2015/01/12 17:33:55.928573 ->[7a:81:57:bc:62:f3]: connection shutting down
weave 2015/01/12 17:33:55.928675 Removing unreachable Peer 7a:81:57:bc:62:f3 (v0) (UID 6237750604680030735)
(repeated over and over)
````

The 2nd peer had just been bounced. The write error on the first peer is when that gets noticed. Subsequent connection attempts by the 2nd peer then appear to trip over the old connection record. Which should have been removed when the write error was detected.

**Comment by rade** [comment]
I wonder whether, instead of tripping over the old connection record, it is actually tripping over a different record which got inserted since then. Seems unlikely though. It would have had to have been an inbound connections (due to the lack of "Attempting connection" message) which hasn't been fully established yet (due to the lack of "established active connection" message).

**Comment by nordbergm** [comment]
Hi @rade,

I'm not sure if this is the same issue, or just very similar, but I'm getting the same log errors when setting up a simple 2 node weave network - but only if I specify a peer both ways. 

On node1 (172.17.8.101):
`weave launch 172.17.8.102`

On node2 (172.17.8.102)
`weave launch 172.17.8.101`

Logs keep repeating the same thing saying the other node's already connected.

```
weave 2015/02/11 19:17:35.206314 Command line options: map[iface:ethwe name:7a:de:ad:c6:dc:cf wait:20]
weave 2015/02/11 19:17:35.206569 Command line peers: [172.17.8.102]
weave 2015/02/11 19:17:35.206666 Communication between peers is unencrypted.
weave 2015/02/11 19:17:35.206705 Our name is 7a:de:ad:c6:dc:cf
weave 2015/02/11 19:17:35.210636 Sniffing traffic on &{14 65535 ethwe 3a:47:03:6a:3e:0b up|broadcast|multicast}
weave 2015/02/11 19:17:35.210712 Discovered our MAC 3a:47:03:6a:3e:0b
weave 2015/02/11 19:17:35.219354 ->[172.17.8.102:6783] attempting connection
weave 2015/02/11 19:17:35.220739 ->[172.17.8.102:6783] error during connection attempt: dial tcp4 172.17.8.102:6783: connection refused
weave 2015/02/11 19:17:36.140159 Discovered local MAC 76:7a:36:54:1b:29
weave 2015/02/11 19:17:36.140951 Discovered local MAC 7a:de:ad:c6:dc:cf
weave 2015/02/11 19:17:37.124966 ->[172.17.8.102:44775] connection accepted
weave 2015/02/11 19:17:37.125367 ->[172.17.8.102:44775] completed handshake with 7a:aa:45:57:9c:f5
weave 2015/02/11 19:17:37.125500 ->[7a:aa:45:57:9c:f5]: connection added
weave 2015/02/11 19:17:37.127711 ->[7a:aa:45:57:9c:f5]: connection fully established
weave 2015/02/11 19:17:37.127826 EMSGSIZE on send, expecting PMTU update (IP packet was 60064 bytes, payload was 60056 bytes)
weave 2015/02/11 19:17:37.127855 ->[7a:aa:45:57:9c:f5]: Effective PMTU set to 1438
weave 2015/02/11 19:17:37.129531 ->[7a:aa:45:57:9c:f5]: Effective PMTU verified at 1438
weave 2015/02/11 19:17:37.562492 Discovered remote MAC 16:ad:fa:af:1f:a3 at 7a:aa:45:57:9c:f5
weave 2015/02/11 19:17:37.997014 ->[172.17.8.102:6783] attempting connection
weave 2015/02/11 19:17:37.999409 ->[172.17.8.102:6783] connection shutting down due to error during handshake: Already have connection to 7a:aa:45:57:9c:f5 at 172.17.8.102:44775
weave 2015/02/11 19:17:38.122945 Discovered remote MAC 7a:aa:45:57:9c:f5 at 7a:aa:45:57:9c:f5
weave 2015/02/11 19:17:41.550101 ->[172.17.8.102:6783] attempting connection
weave 2015/02/11 19:17:41.552373 ->[172.17.8.102:6783] connection shutting down due to error during handshake: Already have connection to 7a:aa:45:57:9c:f5 at 172.17.8.102:44775
weave 2015/02/11 19:17:46.592180 ->[172.17.8.102:6783] attempting connection
weave 2015/02/11 19:17:46.595065 ->[172.17.8.102:6783] connection shutting down due to error during handshake: Already have connection to 7a:aa:45:57:9c:f5 at 172.17.8.102:44775
```

If I instead start node1 without any peers and node2 with the first one as a peer, everything is stable.

On node1 (172.17.8.101):
`weave launch`

On node2 (172.17.8.102)
`weave launch 172.17.8.101`

Let me know if this is relevant and I can help test.

**Comment by rade** [comment]
@nordbergm 
> Logs keep repeating the same thing saying the other node's already connected.

And is it? Check `weave status` on both nodes.

The log message itself isn't an indication of a problem. This issue is about the situation where the message appears even though the nodes *aren't* connected.

**Comment by awh** [comment]
I've just replicated @nordbergm's result - I end up with two peers both of which report that there are two peers in the network which are connected to each other, however one of them is also trying to reconnect periodically to the other. Not sure yet if the problem is related to the original issue, investigating further...

**Comment by awh** [comment]
On the original issue - I think it is definitely the old connection record for two reasons:

1. The remote ephemeral port mentioned by the first host is the same in the initial write error and in the subsequent rejections - `55178`
2. There is no `connection deleted` message from the first host after the write error, which implies that `LocalPeer.handleDeleteConnection` has not been called

I can't reproduce this myself - I always get a `connection deleted` on the first host immediately following the shutdown due to connection reset by peer (albeit from a read rather than a write attempt, which could be pertinent). The code seems to have been refactored a bit since then, I wonder if it was fixed inadvertently? Will investigate further...

**Comment by awh** [comment]
Scratch reason 2 above - I've checked out a version of the source prior to the logging improvement merge, and it is very substantially different. As far as I can tell, the problem reported by @nordbergm is a different issue, I am going to raise that separately. @rade are you happy to close this as cannot reproduce in current version?

**Comment by rade** [comment]
>  @rade are you happy to close this as cannot reproduce in current version?

Yes.
