### ISSUE TITLE
Make Weave easier to deploy by bundling `curl` tool

### ISSUE THREAD

**Issue by bboreham** [zettio/weave#351]
We package `ethtool` and `conntrack` in a container; we should try to add `curl` to that set.

**Comment by rade** [comment]
curl is actually quite easy to build and link statically...

````
./configure --without-ssl --disable-shared
make
rm src/curl
make LDFLAGS=-all-static
````

does the trick.

There are [a few warnings](http://curl.haxx.se/mail/lib-2012-01/0160.html), but they look safe to ignore for our usage.

The resulting executable is 1.6M.
