### ISSUE TITLE
[dns] Add the ability to specify multiple dns names for 'weave run --with-dns'

### ISSUE THREAD

**Issue by yaronr** [zettio/weave#365]
In some use cases, it is very useful to be able to assign multiple DNS names to a single host.

An example, would be:
Having multiple instances of Mesos/Marathon, which require distinct name (like 'marathon-{1..n}'), but at the same time, all having a common 'marathon.weave.local' name as well, since clients don't care and don't want to know how many instances there are, and what's their unique names.

Currently this is solvable using the REST API of weavedns (-X PUT), but that's cumbersome and inconvenient (and error prone).

**Comment by rade** [comment]
This is covered by #364.
