### ISSUE TITLE
[dns] Add the ability to specify domain name, other than .weave.local

### ISSUE THREAD

**Issue by yaronr** [zettio/weave#366]
Something like:
/opt/weave/weave launch-dns $ip/$subnet --domain=multicloud.local

**Comment by squaremo** [comment]
Why does this matter?

**Comment by yaronr** [comment]
Branding, readability
I could see customers wanting to put names that are meaningful to them.

**Comment by rade** [comment]
As @squaremo said, the domain should be almost invisible, and we are planning to make it even more so, to the point where it wouldn't appear in any of the current examples.

Where do you see it show up in a way that affects "branding, readability"?

**Comment by squaremo** [comment]
> Where do you see it show up in a way that affects "branding, readability"?

Well it does as things stand, since one has to use `--hostname=foo.weave.local`. As you say @rade, we are keen to make that invisible to the extent that we can.

However, it seems likely that it will nonetheless "leak", in particular when integrating with other systems, or using weave(DNS) in unanticipated scenarios. So if it's a serious -- albeit cosmetic -- concern, we should consider it.

**Comment by rade** [comment]
Happy to consider it, but it's likely to get more attention if we have a compelling example of weave.local showing up somewhere *other* than `weave run` (since we are planning to remove it from there), where it affects "branding, readability".

**Comment by yaronr** [comment]
Hi
Example of a location OTHER than weave run:
I need some of my services to have multiple names. When running a Mesos cluster, for ex, I have 3 Mesos masters: mesos-master-{1..3}. They need to have a unique name (for leader election, UI, etc), but their clients don't really care or need to know the specifics of that - they just need a Mesos Master. Therefore, I set two fqdn's for each master: a unique one (mesos-master-%i) and a generic one (mesos-master).  The same goes (and is even more important) for Marathon.
To do that, I set the unique name via the hostname, as --host=mesos-master-1.weave.local, and also in a sidekick process, that sets the second name to mesos-master.weave.local (via weave dns REST api).

This is just an example.

Now, the clients, all have to have dns search of weave.local, or - to lookup services using FQDN which means putting .weave.local again in many places. (you could think of cases where clients will not want to change their DNS search).

etc etc.

If I recall correctly, other Docker service discovery solutions allow configuring the network name.

**Comment by BrunoBonacci** [comment]
+1
for ability to set domain names

**Comment by squaremo** [comment]
Fixed in PR #394

**Comment by bboreham** [comment]
This has broken the default functionality when you don't specify a domain.

**Comment by yaronr** [comment]
Thank you guys!

**Comment by rade** [comment]
[Somebody on IRC](https://botbot.me/freenode/weavenetwork/2015-03-17/?msg=34400750&page=2) has actually provided quite a compelling reason for wanting vanity domains: in order to be able to use ssl certs for specific domains.
