### ISSUE TITLE
Why is weave not working in this scenario?

### ISSUE THREAD

**Issue by servermeta** [zettio/weave#368]
I'm trying to assign an ip to a docker container and expose it to the public, but I cant get it to work.

I created a new docker host, called aldebaran, with ubuntu 14.04 and the latest docker.

root@aldebaran:~# weave launch
OK!
root@aldebaran:~#  C=$(weave run 10.0.1.1/24 -t -i nginx)
OK!
root@aldebaran:~# weave expose 10.0.1.1/24
OK!
root@aldebaran:~# ping 10.0.1.1
OK!
root@aldebaran:~# ping 172.17.0.3
OK!
root@aldebaran:~# curl 172.17.0.3
OK!
root@aldebaran:~# curl 10.0.1.1
curl: (7) Failed to connect to 10.0.1.1 port 80: Connection refused

What am I doing wrong? It works in the default example, why is not working here?

**Comment by rade** [comment]
From [the docs for `expose`](http://zettio.github.io/weave/features.html#host-network-integration)
>  we run `expose` choosing an *unused* IP address in the application subnet

and from [the docs for service export](http://zettio.github.io/weave/features.html#service-export)
> we add a NAT rule to route from the outside world to the destination container (example ...)

Do those two things and it should work.

Let me know what we should have said in the docs to avoid the trap you fell into.

**Comment by rade** [comment]
> Do those two things and it should work.

(And the first step alone is sufficient if you only need to access the container from the host, which is what you do in your transcript)

**Comment by servermeta** [comment]
thank you @rade! you are doing REALLY an excellent job with this app. It's really helping me with my project, and the code is very well written and much simpler than docker, really helping me in learning advanced Go.

I'm trying to create an open source docker web interface, and weave is just what I was looking for.

My goal is to try to assign a local, static IP accessible from the host, so I can setup iptables rules to make it accessible to the internet. I'm starting just from host accessibility, as I already know how to use Iptables, but I'm stuck.

You say I gotta use an unused IP, but that IP is only used by that container. The only thing that I'm doing different from the screencast, is that I'm using curl on the host and not on the other VMs.

Given this is a fresh install, with no used IPs, can you help me understand how do I assign an IP in the format 10.x.x.x to a container, so that such IP is accessible from the host? If my commands were wrong how should I have done it?

Consider I'm really noob, so maybe a more experencied user wouldn't have met this problems, but I think some HowTos could be helpful, and I will be more than glad in helping you :)

**Comment by rade** [comment]
> You say I gotta use an unused IP, but that IP is only used by that container.

It's not unused then, is it?

`weave expose` exposes an *entire sub-net*. The given IP address needs to be unused since it serves as a "gateway" into that sub-net.

> how do I assign an IP in the format 10.x.x.x to a container, so that such IP is accessible from the host?

There is nothing wrong with your IP assignment to the container. The problem is that you are using the *same* IP in `expose`. Choose a different, unused IP on the same sub-net.

**Comment by servermeta** [comment]
root@aldebaran:~# weave expose 10.0.1.2/24
OK!
root@aldebaran:~# ping 10.0.1.2
OK!
root@aldebaran:~# curl 10.0.1.2
curl: (7) Failed to connect to 10.0.1.2 port 80: Connection refused


10.0.1.2 is in the same sub-net right?

**Comment by servermeta** [comment]
root@aldebaran:~# weave attach 10.0.1.2/24 9e9
root@aldebaran:~# curl 10.0.1.2
curl: (7) Failed to connect to 10.0.1.2 port 80: Connection refused

doesnt work either. I'm sorry if I'm sounding really noob, but I have just very basic understanding of networking, I repeated the step you made in the screencast, step by step, and it doesnt work. I'm sure I will laugh about my noobishness in 30 minutes, but for now it's just frustrating that it isnt working :p

**Comment by rade** [comment]
Trying curling to 10.0.1.1.

**Comment by servermeta** [comment]
It's the first thing I tried, as you can see in the first question. It's still not working :(

root@aldebaran:~# curl 10.0.1.1
curl: (7) Failed to connect to 10.0.1.1 port 80: Connection refuse

**Comment by rade** [comment]
Try exposing 10.0.1.2/24 and pinging 10.0.1.1.

Notice how in [the docs](http://zettio.github.io/weave/features.html#host-network-integration) the example exposes 10.0.1.102 but then pings 10.0.1.2 and 10.0.1.1.

**Comment by servermeta** [comment]
I started from the ground up.

C=$(weave run 10.0.2.1/24 -t -i nginx)
OK!
weave expose 10.0.2.2/24
OK!
curl 10.0.2.1
OK!!!

it works!!! great!!! So I gotta expose an unused ip, from the same subnet, because it will act as gateway?

So a smart way to do it, would be to assign a /30 size subnet to each docker container, so it has 2 IPs, one for the container, and one for the gateway? 

I feel like a linux rockstar thanks to you.

**Comment by rade** [comment]
> So a smart way to do it, would be to assign a /30 size subnet to each docker container, so it has 2 IPs, one for the container, and one for the gateway? 

Then none of your containers would be able to talk to *each other*, since they'd all be on different sub-nets. Perhaps that is what you want, but it seems a bit unusual.

As I said, `expose` acts on an entire sub-net; so a more typical application is to place a bunch of containers in a common sub-net, giving them each their own IP, and then use one extra IP from the same sub-net to expose the entire sub-net, i.e. all containers, to the host.

**Comment by servermeta** [comment]
Very good point!

Is there a way with weave to let 2 subnet talk to each other? Or should I use the usual ip route tools?

**Comment by rade** [comment]
> Is there a way with weave to let 2 subnet talk to each other?

Nope. Though you can [assgin containers IPs on more than one sub-net](http://zettio.github.io/weave/features.html#dynamic-network-attachment).

**Comment by servermeta** [comment]
thank you rade. You built an exceptional project.

I can help three ways:

1) Create a blog post/git commit with a zero to start explanation on how to use weave, for n00bs like me.

2) I can ask a friend to make you a logo for this project for free, if you want, as I think it would greatly help spread your project (think a nice clickable logo in my blog post, or on the list of the technologies used in my docker web panel)

3) Help you to create a better website? It's already pretty good, but you can always improve, and this is one of  the few stuff I can help you with

this project solved me a lot of troubles, and I'm willing to help it anyway I can :)

**Comment by rade** [comment]
@servermeta Thanks for the kind offer. A blog post would be great. Email us at help@weave.works if you want to discuss the content or would like us to review the post prior to publication.
