### ISSUE TITLE
Unable to run 'make' on Fedora Distro

### ISSUE THREAD

**Issue by aanm** [zettio/weave#370]
Hi,
I was unable to run 'make' on Fedora.
It returned:
/bin/ld: cannot find -lpcap
Although there's a libpcap-devel package, it doesn't provide the "libpcap.a".
To fix it, you just have to build it from libpcap.a from sources (http://www.tcpdump.org/release/).
And copy it to /usr/lib/libpcap.a

**Comment by rade** [comment]
The other issue was the absence of the static libs for libpthread and libc. This was fixed by installing glibc-static.

**Comment by rade** [comment]
We should update [our docs](http://zettio.github.io/weave/building.html)

**Comment by rade** [comment]
@dpw iirc you mentioned that you ran into a bunch of problems building weave on Fedora. Anything other than the above?

**Comment by dpw** [comment]
I'm not sure.

But we shouldn't be recommending that people install non-distro libs into system-wide locations, because then we risk breaking stuff for them.  Which means you need to set the appropriate environment variables to 'go build' to make it use the alternate libpcap and associated header file.

If we are going to document how to build under other distros, it might be better simply to recommend building in a debian/ubuntu container.

**Comment by rade** [comment]
> If we are going to document how to build under other distros, it might be better simply to recommend building in a debian/ubuntu container.

Well, we already have the vagrant instructions.

Perhaps we just need to tweak the docs in some other way, e.g. put the vagrant section first.

**Comment by aanm** [comment]
@dpw 
If I may, and in my humble opinion, one of the points of weave's favor should be to have docker networking running on multiple hosts. That multi architecture structure should allow weave to run on different distros and not only on debian/ubuntu. I think it's better to fix those issues now than in the future when it could probably be irreversible.

@rade 
Yes, I think it would probably be better to have the "easy" mode first and then distros related.

**Comment by rade** [comment]
@aanm you don't need to build weave in order to run it.

**Comment by aanm** [comment]
@rade Oh yeah, I completely forgot about that.
@dpw Forget what I said :-)

**Comment by dpw** [comment]
> Well, we already have the vagrant instructions.
> 
> Perhaps we just need to tweak the docs in some other way, e.g. put the vagrant section first.

Haven't you heard my opinion of vagrant? Or are you just teasing?

What's wrong with recommending building in a container?

**Comment by rade** [comment]
> What's wrong with recommending building in a container?

Nothing. But somebody would actually have to make that work and document it.

**Comment by aanm** [comment]
I thought you were talking about using weave (as release) inside vagrant and not building it

**Comment by dpw** [comment]
> @dpw iirc you mentioned that you ran into a bunch of problems building weave on Fedora. Anything other than the above?

I suspect that the WEAVETOOLS_EXES build step doesn't work under fedora with selinux enabled (due to the use of the `docker run -v` option).

**Comment by rade** [comment]
This has been superseded by #387.
