### ISSUE TITLE
Make provisioning simpler with retrying peer resolver

### ISSUE THREAD

**Issue by errordeveloper** [zettio/weave#389]
Currently `weave launch host-01` will fail if we cannot resolve `host-01` right away, on the grounds that user might have mistyped the hostname argument.

When provisioning in certain public clouds, i.e. GCE and Azure, there is free native DNS that one can use, thereby it's very easy and can be utilised without having static IPs.

So I can provision nodes with init scripts that read peer names from a files on disk, where the names are local DNS names. During provisioning, I don't necessarily have the control of the order, so DNS records might not be created for some peers yet.

**Comment by rade** [comment]
This seems to be substantially the same as #112, no?

**Comment by errordeveloper** [comment]
@rade, true, should have done the search first... It does give #112 a practical angle though.
