### ISSUE TITLE
weave 0.9.0 dosen't support --read-only argument of docker 1.5.0

### ISSUE THREAD

**Issue by threadflow** [zettio/weave#398]
I am running docker 1.5.0 build a8a31ef and weave 0.9.0.

When running this command: 
`docker run --read-only -v $PWD/volumes:/var/test busybox ls /var`
got the result expected:
```
cache
lib
lock
log
pcmcia
run
spool
test
tmp
www
```

When running this:
`weave run 10.10.24.88/24 --read-only -v $PWD/volumes:/var/test busybox ls /var`
got error message:
```
Container df8d6b7229d904f4ed0485cbb42bc2e0e278e2631ea6d2331494c4c2ac95e166 not running.
```

**Comment by bboreham** [comment]
I think you have stumbled across the fact that weave always runs containers in background mode, i.e. it adds `-d` to the arguments.  This is discussed at #251.

The `ls` that you ran had completed and exited before `weave` finished setting up the network for that container, so `weave` pointed this out to you.  If you do `docker logs df8d` you should see the output.

Weave should be indifferent to the new `--read-only` flag.
