### ISSUE TITLE
Getting "Driver aufs failed to remove root filesystem" errors when doing "weave attach"

### ISSUE THREAD

**Issue by fermayo** [zettio/weave#408]
Sometimes, when we do “weave attach”, we get the following error message:

```
Failure during network configuration for container 175f21e52c001687c93351bba777dff4cdfcd9883d6c1b2336c3950c7e27be22:
2015-02-20T10:12:22.270753379Z time="2015-02-20T10:12:22Z" level="fatal" msg="Error response from daemon: Cannot destroy container 71e7a68d502251769e20b830719704b3bd207e1b9cdffda6b761a8370cb3e0e6: Driver aufs failed to remove root filesystem 71e7a68d502251769e20b830719704b3bd207e1b9cdffda6b761a8370cb3e0e6: rename /var/lib/docker/aufs/mnt/71e7a68d502251769e20b830719704b3bd207e1b9cdffda6b761a8370cb3e0e6 /var/lib/docker/aufs/mnt/71e7a68d502251769e20b830719704b3bd207e1b9cdffda6b761a8370cb3e0e6-removing: device or resource busy" 
```

Retrying the command usually works the second time. But some other times, it fails with this:
```
time="2015-02-20T12:25:00Z" level="fatal" msg="Error response from daemon: Cannot destroy container 6f8838dcae38d3d4f10beba6bd3e346234aad07e6e8a75b312ff2618f206e4cb: Driver aufs failed to remove root filesystem 6f8838dcae38d3d4f10beba6bd3e346234aad07e6e8a75b312ff2618f206e4cb: rename /var/lib/docker/aufs/mnt/6f8838dcae38d3d4f10beba6bd3e346234aad07e6e8a75b312ff2618f206e4cb /var/lib/docker/aufs/mnt/6f8838dcae38d3d4f10beba6bd3e346234aad07e6e8a75b312ff2618f206e4cb-removing: device or resource busy" 
```

Although we get that last error message, the attach is being executed successfully and there are no containers left behind. We are using `docker 1.5.0`.

Any ideas? Maybe related to https://github.com/zettio/weave/issues/378?

**Comment by bboreham** [comment]
It looks like it is trying to destroy one of the containers used to execute sub-commands by the `weave` script, such as `ethtool`.  Certainly the message suggests it is going wrong deep in the bowels of Docker.

Yes, both this and #378 could have a common cause, although nobody reported any error messages against #378.

**Comment by fermayo** [comment]
Is there anything I can do to troubleshoot this? Seems to be happening when I attach several containers in parallel.

**Comment by rade** [comment]
Sit back and wait for the associated [docker bug](https://github.com/docker/docker/issues/9665) to get fixed. -> closing this one.

**Comment by dpw** [comment]
I wonder if there are any other errors shown in the docker daemon logs when this error occurs? Googling for "aufs failed to remove root filesystem" suggests that it has been a symptom of many different docker issues (e.g. some error happens in the docker daemon, it tries to delete the container, but fails because the container filesystem is still in use, and you get this error message).  So to solve this, we need to identify the underlying issue.
