### ISSUE TITLE
Another deadlock

### ISSUE THREAD

**Issue by bboreham** [zettio/weave#415]
I created this situation by instantiating 22 peers and connecting them all up at once; this resulted in a number of connections being added and then removed; each operation results in gossip to all peers.

Excerpt from logs showing rapid sequence of events:

````
weave 2015/02/24 14:38:38.008336 ->[1a:9a:a4:30:2f:2c]: connection shutting down due to error: write tcp4 172.17.2.10:46783: connection reset by peer
weave 2015/02/24 14:38:38.008396 ->[02:31:50:de:53:4f]: connection shutting down due to error: write tcp4 172.17.2.6:41884: connection reset by peer
weave 2015/02/24 14:38:38.008865 ->[b2:1e:e1:32:d8:2c]: connection shutting down due to error: Connection limit reached (10)
weave 2015/02/24 14:38:38.008883 ->[1e:97:15:ae:b3:63]: connection shutting down due to error: Connection limit reached (10)
weave 2015/02/24 14:38:38.008901 ->[6a:5e:7b:a5:0b:e9]: connection shutting down due to error: Connection limit reached (10)
weave 2015/02/24 14:38:38.009185 ->[f2:63:b4:c6:86:05]: connection shutting down due to error: Connection limit reached (10)
weave 2015/02/24 14:38:38.009424 ->[2a:b5:e7:be:cd:b8]: connection shutting down due to error: Connection limit reached (10)
weave 2015/02/24 14:38:38.009977 ->[ca:a6:00:31:4a:59]: connection shutting down due to error: Connection limit reached (10)
````

The deadlock is that LocalPeer queryLoop is blocked on sending a topology update gossip message to a connection:

````
goroutine 21 [select, 32 minutes]:
github.com/zettio/weave/router.(*LocalConnection).sendQuery(0xc2093905a0, 0x0, 0x82d560, 0xc20a161440)
	zettio/weave/router/connection.go:196 +0xdf
github.com/zettio/weave/router.(*LocalConnection).SendProtocolMsg(0xc2093905a0, 0x5, 0xc20a168380, 0x2cc, 0x33a)
	zettio/weave/router/connection.go:228 +0x70
github.com/zettio/weave/router.func·008(0x3e1d5fea9d09, 0x7f00c85ba478, 0xc2093905a0)
	zettio/weave/router/gossip.go:121 +0x73
github.com/zettio/weave/router.(*Peer).ForEachConnection(0xc208004300, 0x7f00ca0e8c88)
	zettio/weave/router/peer.go:78 +0xf6
github.com/zettio/weave/router.(*GossipChannel).SendGossipMsg(0xc209085590, 0xc2099ac500, 0x2b2, 0x4be)
	zettio/weave/router/gossip.go:122 +0xb8
github.com/zettio/weave/router.(*LocalPeer).broadcastPeerUpdate(0xc2090891a0, 0x7f00ca0e8df0, 0x1, 0x1)
	zettio/weave/router/local_peer.go:281 +0x1d7
github.com/zettio/weave/router.(*LocalPeer).handleAddConnection(0xc2090891a0, 0x7f00c85ba478, 0xc2091123c0, 0xc2091123c0)
	zettio/weave/router/local_peer.go:230 +0x559
github.com/zettio/weave/router.(*LocalPeer).queryLoop(0xc2090891a0, 0xc2081280e0)
	zettio/weave/router/local_peer.go:171 +0x146
created by github.com/zettio/weave/router.(*LocalPeer).Start
	zettio/weave/router/local_peer.go:28 +0x53
````

while the Connection is blocked trying to send a setEstablished message to LocalPeer:

````
goroutine 63 [chan send, 32 minutes]:
github.com/zettio/weave/router.(*LocalConnection).handleSetEstablished(0xc2093905a0, 0x0, 0x0)
	zettio/weave/router/connection.go:363 +0x13c
github.com/zettio/weave/router.(*LocalConnection).queryLoop(0xc2093905a0, 0xc20925ae00, 0x0, 0x0)
	zettio/weave/router/connection.go:309 +0x19a
github.com/zettio/weave/router.(*LocalConnection).run(0xc2093905a0, 0xc20925ae00, 0xc209314480, 0x84b501)
	zettio/weave/router/connection.go:275 +0x684
created by github.com/zettio/weave/router.(*LocalConnection).Start
	zettio/weave/router/connection.go:131 +0x9c
````

There are a bunch more connections trying to send a Shutdown message, which is consistent with the theory that this happens when a lot of connections are shut down close together in time:

````
goroutine 46 [chan send, 125 minutes]:
github.com/zettio/weave/router.(*LocalConnection).handleShutdown(0xc20927a870)
	/home/bryan/golang/src/github.com/zettio/weave/router/connection.go:400 +0x191
github.com/zettio/weave/router.(*LocalConnection).run(0xc20927a870, 0xc2093136e0, 0xc209313740, 0x884701)
	/home/bryan/golang/src/github.com/zettio/weave/router/connection.go:280 +0x9f7
created by github.com/zettio/weave/router.(*LocalConnection).Start
	/home/bryan/golang/src/github.com/zettio/weave/router/connection.go:131 +0xdd
````

I can recreate this on demand.

**Comment by bboreham** [comment]
An idea to prevent gossip messages clogging up the Connection channel:

We know that a newer gossip message, if available, should be sent in preference to an older one.  There is no point queueing them up.  Create an intermediary that runs code like this, where `in` and `out` are unbuffered Go channels:

````
for {
    val <- in
    inner: 
    for {
        select {
            val <- in:
            out <- val:
                break inner
        }
    }
}
````

then put one of these between GossipChannel.SendGossipMessage and LocalConnection.SendProtocolMessage.  I suspect there should be one per connection per GossipChannel, which complicates matters somewhat.

**Comment by rade** [comment]
Do you have any evidence to suggest that we actually have gossip messages queueing up?

Also, surely this should only ever be an issue for topology gossip since that isn't doing proper gossip. Normal use of gossip channels would broadcast incremental changes, and send the complete state on a timer.

**Comment by bboreham** [comment]
Each time I have repeated this deadlock, I can see several blocked goroutines with SendGossipMsg() on the stack.  I don't know for sure what the other contents of the LocalConnection channel buffer are, but I can't see anything else that would get enqueued at any frequency.

The limiting factor for this deadlock is the 16 slots in the channel, not the size of the messages.

**Comment by bboreham** [comment]
Further thoughts:

For gossip channels sending incremental updates, we could extend the eliding mechanism to merge the new value instead of replacing it. 

For situations where gossip messages are sent rapidly that cannot be elided, we'd need a different solution. 

I'll look at instrumenting the channel to get better evidence of how it breaks.

**Comment by rade** [comment]
> Each time I have repeated this deadlock, I can see several blocked goroutines with SendGossipMsg() on the stack.

Where's the deadlock? i.e. what's the cycle of locks which prevents the connection actor from progressing?

**Comment by rade** [comment]
> Where's the deadlock?

Ah, just noticed you determined that already in your first comment.

**Comment by bboreham** [comment]
I added a circular buffer to capture what goes into the Connection channel, and at the point of deadlock every non-empty channel has N or N-1 gossip entries in it.  

I saw one Shutdown message in the queue, which suggests a minor tweak to call `close(finished)` on the client side, but that won't shift the needle on the overall problem.
