### ISSUE TITLE
Weave kills reverse proxy

### ISSUE THREAD

**Issue by setiseta** [zettio/weave#422]
If weave is startet its not possible to start nginx-reverse proxy (jwilder)

**Comment by squaremo** [comment]
Hi -- would you post a brief "steps to reproduce" shell transcript here, just to clarify?

**Comment by setiseta** [comment]
hi, 
yeas of coure, sorry for the small information.

i'm using nginx-proxy to manage simple containers with webfrontend.
here is the nginx cmd:
docker run -d \
        -p 80:80 \
        -v /var/run/docker.sock:/tmp/docker.sock \
        --name nginx \
        --restart=always \
        jwilder/nginx-proxy

if i launch weave it gets "killed" and is always restarting.
if i stop weave, it gets up again.
so it seems that there is a compatibility problem.

hope this is the right place for this problem.

thx

**Comment by squaremo** [comment]
Naively, I did

```
$ docker run -d \
  -p 80:80 \
  -v /var/run/docker.sock:/tmp/docker.sock \
  --name nginx \
  --restart=always \
  jwilder/nginx-proxy
$ sudo weave launch
```

and it looks OK. `docker logs -f nginx` shows that it's ignoring all the containers weave uses to do various things.

Is there something else about your deployment that might be a factor? E.g., what else are you using weave for; do you have other port mappings or routing rules; what other containers are you running?

**Comment by setiseta** [comment]
hm, ok strange thing.
so i've retested "from scratch".
and got same behavier with these steps:
 - installaiton of fedora server 21
 - disabled selinux
 - disabled firewalld
 - enabled docker
 - yum upgrade 
 - reboot
 - nginx startup as above
 - weave launch

same thing:
zettio/weave:0.9.0 -> Up About a minute
jwilder/nginx-proxy:latest -> Restarting (0) 46 seconds ago

what is different on your machine, that it works?

thx.

**Comment by squaremo** [comment]
> what is different on your machine, that it works?

I'm using a VM with Ubuntu, so that's one thing. What's in the nginx and weave logs? (maybe gist them)

**Comment by setiseta** [comment]
nginx log:
forego     | starting nginx.1 on port 5000
forego     | starting dockergen.1 on port 5100
dockergen.1 | panic: runtime error: index out of range
dockergen.1 |
dockergen.1 | goroutine 16 [running]:
dockergen.1 | runtime.panic(0x779be0, 0x9bfafc)
dockergen.1 |   /usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
dockergen.1 | main.getContainers(0xc20804c200, 0x0, 0x0, 0x0, 0x0, 0x0)
dockergen.1 |   /home/jwilder/go/src/github.com/jwilder/docker-gen/docker_client.go:144 +0xa94
dockergen.1 | main.generateFromContainers(0xc20804c200)
dockergen.1 |   /home/jwilder/go/src/github.com/jwilder/docker-gen/docker-gen.go:150 +0x35
dockergen.1 | main.main()
dockergen.1 |   /home/jwilder/go/src/github.com/jwilder/docker-gen/docker-gen.go:388 +0x40c
dockergen.1 |
dockergen.1 | goroutine 17 [runnable]:
dockergen.1 | runtime.MHeap_Scavenger()
dockergen.1 |   /usr/local/go/src/pkg/runtime/mheap.c:507
dockergen.1 | runtime.goexit()
dockergen.1 |   /usr/local/go/src/pkg/runtime/proc.c:1445
dockergen.1 |
dockergen.1 | goroutine 18 [runnable]:
dockergen.1 | bgsweep()
dockergen.1 |   /usr/local/go/src/pkg/runtime/mgc0.c:1976
dockergen.1 | runtime.goexit()
dockergen.1 |   /usr/local/go/src/pkg/runtime/proc.c:1445
dockergen.1 |
dockergen.1 | goroutine 19 [runnable]:
dockergen.1 | runfinq()
dockergen.1 |   /usr/local/go/src/pkg/runtime/mgc0.c:2606
dockergen.1 | runtime.goexit()
dockergen.1 |   /usr/local/go/src/pkg/runtime/proc.c:1445

weave seems good. no errors.
but something happens to nginx if weave is running.

any idea?

**Comment by squaremo** [comment]
Weave starts and stops a bunch of containers to do its work. Is it possible that just starting and stopping any container will break nginx? E.g., `docker run --rm ubuntu echo hello`

**Comment by setiseta** [comment]
no this is not a problem. tried with your command, and normally its running as reverse proxy for a bunch of tomcat nodes.
and if its running fine on your ubuntu machine, i think there is a compability problem with fedora 21, waeve and nginx.
don't know where to search first.

**Comment by squaremo** [comment]
The line numbers in that stack trace don't appear to correspond with a (recent) tagged image of jwilder/nginx-proxy. Can you tell me where that image comes from?

**Comment by squaremo** [comment]
My best guess is that docker-gen is assuming something about the container config that doesn't hold in weave's case. Possibly it's this line, or its ancestor: https://github.com/jwilder/docker-gen/blob/0.3.7/docker_client.go#L152 (assumes that every env entry is of the form "X=Y"), which is at least close to the lines in the stack trace.

What does `docker inspect weave` give you?

**Comment by setiseta** [comment]
ok i've created an issue on jwilder's repo. maybe someone there can help.

here is the inspect output:
[{
    "AppArmorProfile": "",
    "Args": [
        "-wait",
        "20",
        "-name",
        "7a:05:af:ce:89:24",
        "-iface",
        "ethwe"
    ],
    "Config": {
        "AttachStderr": false,
        "AttachStdin": false,
        "AttachStdout": false,
        "Cmd": [
            "-name",
            "7a:05:af:ce:89:24",
            "-iface",
            "ethwe"
        ],
        "CpuShares": 0,
        "Cpuset": "",
        "Domainname": "",
        "Entrypoint": [
            "/home/weave/weaver",
            "-wait",
            "20"
        ],
        "Env": [
            "WEAVE_PASSWORD",
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        ],
        "ExposedPorts": {
            "6783/tcp": {},
            "6783/udp": {}
        },
        "Hostname": "cc0f45b9ab1a",
        "Image": "zettio/weave:0.9.0",
        "MacAddress": "",
        "Memory": 0,
        "MemorySwap": 0,
        "NetworkDisabled": false,
        "OnBuild": null,
        "OpenStdin": false,
        "PortSpecs": null,
        "StdinOnce": false,
        "Tty": false,
        "User": "",
        "Volumes": null,
        "WorkingDir": "/home/weave"
    },
    "Created": "2015-02-28T06:49:49.390789987Z",
    "Driver": "devicemapper",
    "ExecDriver": "native-0.2",
    "ExecIDs": null,
    "HostConfig": {
        "Binds": null,
        "CapAdd": null,
        "CapDrop": null,
        "ContainerIDFile": "",
        "Devices": [],
        "Dns": null,
        "DnsSearch": null,
        "ExtraHosts": null,
        "IpcMode": "",
        "Links": null,
        "LxcConf": [],
        "NetworkMode": "bridge",
        "PidMode": "",
        "PortBindings": {
            "6783/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "6783"
                }
            ],
            "6783/udp": [
                {
                    "HostIp": "",
                    "HostPort": "6783"
                }
            ]
        },
        "Privileged": true,
        "PublishAllPorts": false,
        "ReadonlyRootfs": false,
        "RestartPolicy": {
            "MaximumRetryCount": 0,
            "Name": ""
        },
        "SecurityOpt": null,
        "VolumesFrom": null
    },
    "HostnamePath": "/var/lib/docker/containers/cc0f45b9ab1a5c1d3acb7fca99edcc6cf29913413294aec075ecb155a25c70dd/hostname",
    "HostsPath": "/var/lib/docker/containers/cc0f45b9ab1a5c1d3acb7fca99edcc6cf29913413294aec075ecb155a25c70dd/hosts",
    "Id": "cc0f45b9ab1a5c1d3acb7fca99edcc6cf29913413294aec075ecb155a25c70dd",
    "Image": "efb52cb2a3b8ea06d625f006942a690ad56bdacb39691071383439994a61f805",
    "MountLabel": "",
    "Name": "/weave",
    "NetworkSettings": {
        "Bridge": "docker0",
        "Gateway": "172.17.42.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAddress": "172.17.0.4",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "fe80::42:acff:fe11:4",
        "LinkLocalIPv6PrefixLen": 64,
        "MacAddress": "02:42:ac:11:00:04",
        "PortMapping": null,
        "Ports": {
            "6783/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "6783"
                }
            ],
            "6783/udp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "6783"
                }
            ]
        }
    },
    "Path": "/home/weave/weaver",
    "ProcessLabel": "",
    "ResolvConfPath": "/var/lib/docker/containers/cc0f45b9ab1a5c1d3acb7fca99edcc6cf29913413294aec075ecb155a25c70dd/resolv.conf",
    "RestartCount": 0,
    "State": {
        "Error": "",
        "ExitCode": 0,
        "FinishedAt": "0001-01-01T00:00:00Z",
        "OOMKilled": false,
        "Paused": false,
        "Pid": 1698,
        "Restarting": false,
        "Running": true,
        "StartedAt": "2015-02-28T06:49:50.052368234Z"
    },
    "Volumes": {},
    "VolumesRW": {}
}
]

**Comment by setiseta** [comment]
with the fix from md5 it works.
