### ISSUE TITLE
Question: access to 10/8 CIDR despite no if with such IP?

### ISSUE THREAD

**Issue by haf** [zettio/weave#431]
I'm experimenting with weave, aiming to use it together with consul to make our docker deployment across a couple of hosts a cluster with failover services running (registrator + consult + weave).

So far I'm in the 'learning' stage, so I have a question, I was hoping you might be able to answer.

I have run 'weave launch' and basically followed all steps in what seems to be *the guide* to weave https://sttts.github.io/docker/weave/mesos/2015/01/22/weave.html.

I haven't been able to:

 - automatically use weave when `docker run` is used

However, this is the state:

![screen shot 2015-03-04 at 11 14 50](https://cloud.githubusercontent.com/assets/193115/6481657/b3c615c2-c25f-11e4-9272-94b1de3dedd4.png)

And when doing a `docker exec` inside `eventstore.0`, which was started with `docker run` as opposed to `weave run` it can still ping 10.0.0.1 -- how does with work out?

```
➜  ops git:(master) dockerip
697ac571ee06	172.17.0.24
1c41103cb271	172.17.0.17
cc079798d2c1	172.17.0.16
5ad6a9d93e56	172.17.0.9
75f4bc57613b	172.17.0.5
➜  ops git:(master) docker exec eventstore.0 ping 10.0.0.1
PING 10.0.0.1 (10.0.0.1) 56(84) bytes of data.
64 bytes from 10.0.0.1: icmp_seq=1 ttl=64 time=0.049 ms
64 bytes from 10.0.0.1: icmp_seq=2 ttl=64 time=0.068 ms
^C%                                                                                           ➜  ops git:(master) docker exec eventstore.0 ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
70: eth0: <BROADCAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:ac:11:00:18 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.24/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe11:18/64 scope link
       valid_lft forever preferred_lft forever
```

PS: it is not my fault that docker named The Registrator "boring torvalds" :8ball:

**Comment by rade** [comment]
> I have run 'weave launch' and basically followed all steps in what seems to be *the guide* to weave https://sttts.github.io/docker/weave/mesos/2015/01/22/weave.html.

The above is quite advanced usage of weave. If you are new to weave I strongly recommend you follow [*our* intro in the README](https://github.com/zettio/weave/blob/master/README.md) to become familiar with it.

**Comment by haf** [comment]
I've followed that intro, too and yes, the output that you've written should come, comes.

**Comment by rade** [comment]
As to your specific question, I suspect the answer can be found in [our docs on application isolation](http://zettio.github.io/weave/features.html#application-isolation), in particular this bit

> By default docker permits communication between containers on the same host, via their docker-assigned IP addresses. For complete isolation between application containers, that feature needs to be disabled by setting `--icc=false` in the docker daemon configuration.

**Comment by haf** [comment]
I see! Let me try it!

**Comment by haf** [comment]
That didn't work. I have this in `/var/lib/boot2docker/profile`:

```
--bridge=weave --fixed-cidr=10.1.0.0/16 --icc=false
```

Doing a `docker run` still spawns a container w/o the weave nic.

Doing a `weave run` spawn a container like expected, with a NIC, `ethwe` with a 10.1.x.x ip (depending on args to run).

Pinging 10.1.0.2 (started above) from the container started with `docker run` doesn't seem to have isolation, despite the flags.

`docker run` still gives ips in the 172.17/16-network.

It might be that the docker daemon in boot2docker isn't reading the /var/lib-file -- but instead from somewhere else entirely.

boot2docker doesn't have the brctl command - perhaps that matters?

Doing a `boot2docker restart` seems to delete the /usr/local/bin/weave file.

**Comment by haf** [comment]
/etc/default/docker didn't work either. New machines are still not getting the right CIDR.

**Comment by haf** [comment]
So it seems that boot2docker is a very strange kind of linux, I'm giving up on it and using the coreos boxes that I'll use in prod instead. They seem differently configured.

**Comment by haf** [comment]
Is there anywhere I can get help faster than this? It'll take many days to learn in this speed.

**Comment by haf** [comment]
I'm going to try Deis and Flannel instead.

**Comment by squaremo** [comment]
> Is there anywhere I can get help faster than this?

You could try (have tried) our IRC channel #weavenetwork on freenode.
