### ISSUE TITLE
First few seconds/.minutes, TCP & UDP mostly fail between containers

### ISSUE THREAD

**Issue by nmarasoiu** [zettio/weave#439]
Hi,

Initially i see alot of Connection refused, and in a few minutes the situation stabilizes.
Do you know what can cause this?

Thank you
Nicu

**Comment by nmarasoiu** [comment]
In fact, only when I restart weave it is happening. If I just restart containers works like a charm.
2 minutes is alot, but maybe if i wait right after weave launch, to scriptically busy-wait until all the virtual ips 10.x.x.x see each other before continuing with weave run instances, then it should be ok

**Comment by rade** [comment]
Some initial delay is expected. But 2 minutes is a lot. Can you post some steps to reproduce that behaviour?

**Comment by rade** [comment]
Could be related to #441.
