### ISSUE TITLE
ufw block

### ISSUE THREAD

**Issue by kesavkolla** [zettio/weave#450]
I've enabled ufw on my ubuntu 14.10 server.  After that I see the following in ufw.log

> [UFW BLOCK] IN=weave OUT=weave PHYSIN=vethwepl8172 PHYSOUT=vethwepl24506 SRC=10.0.20.1 DST=10.0.20.254 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=38255 DF PROTO=TCP SPT=36452 DPT=5432 WINDOW=43690 RES=0x00 SYN URGP=0

I don't know what's the implication of this.  I'm still able to communicate between containers.  ufw.log is growing at a fast pace that's only effect I can see.

Is there any way to fix this?

Thanks in advance

**Comment by rade** [comment]
I know nothing about ufw, but taking the log message at face value, it indicates that a packet was blocked on a TCP connection between two containers on the same machine. The connection was made between weave IP & ports 10.0.20.1:36452 and 10.0.20.254:5432.

I am surprised this doesn't break anything in your app.

You'll want to find a way to stop ufw from touching any packets traversing the weave bridge - notice the "IN=weave OUT=weave". What's strange is that afaict we looked into a similar problem as part of #96, and came up with https://github.com/zettio/weave/blob/master/weave#L137, which, on the surface, appears to do exactly what I am suggesting.

**Comment by kesavkolla** [comment]
Even though it shows in the log file block but really there is no interruption in my app.  This particular traffic is for PostgreSQL database.  I'm able to connect to the database and able to execute queries.

May be ufw logs it but iptables allow it.  Even I don't know much about ufw that's why I'm looking for suggestions.

Thanks.

**Comment by rade** [comment]
> May be ufw logs it but iptables allow it.

I was wondering that too.

> Even I don't know much about ufw that's why I'm looking for suggestions.

I'm afraid your guess is as good as mine. Resolving this issue will require digging into ufw. If you do find out how to prevent these log messages, please do let us know and we'll update our code/docs accordingly.

**Comment by rade** [comment]
I am closing this. Please re-open if there are any new pertinent discoveries.
