### ISSUE TITLE
Hang on send to nil chan verifyPMTU

### ISSUE THREAD

**Issue by bboreham** [zettio/weave#464]
I have a few instances of this stack trace, obtained while stress-testing Weave.  No idea yet how it can get into this state, but it cannot get out:

````
github.com/zettio/weave/router.(*LocalConnection).handleProtocolMsg(0xc209b7c780, 0xc208f00e04, 0xc208f00ef1, 0x2, 0x2, 0x0, 0x0)
	github.com/zettio/weave/router/connection.go:464 +0x432
github.com/zettio/weave/router.(*LocalConnection).receiveTCP(0xc209b7c780, 0xc209789480)
	github.com/zettio/weave/router/connection.go:435 +0x3ce
github.com/zettio/weave/router.func·001()
	github.com/zettio/weave/router/connection.go:252 +0x169
created by github.com/zettio/weave/router.(*LocalConnection).run
	github.com/zettio/weave/router/connection.go:253 +0x4ff
````

The line it's stuck on is:

````
	case ProtocolPMTUVerified:
		conn.verifyPMTU <- int(binary.BigEndian.Uint16(payload))
````

**Comment by rade** [comment]
There should be some other stuck processes. Please list them.

**Comment by rade** [comment]
@bboreham have you seen this recently?

For that code to block, the forwarder must be blocked or have terminated. But it must also have sent at least 16 pmtu verification packets, which takes at least 2^16*10ms, i.e. approximately 10 minutes, during which time it obviously wasn't blocked or dead. And something must have held up these packets or the reply from the other end, or the local processing thereof.

So something weird must have been going on.

I shall fix the "terminated forwarder" case and declare victory in the absence of further evidence.
