### ISSUE TITLE
Hosts file

### ISSUE THREAD

**Issue by pixie79** [zettio/weave#483]
When starting a container via weave, weave should update the container so that the ip used for the container is the ip given in /etc/hosts inside the container.

i.e If i start the container with the IP 192.168.1.1 then inside the container the /etc/hosts should read
192.168.1.1 name.example.com name

It should not list the VM's private docker IP as name.example.com, otherwise services that bind by name will bind to the wrong interface and not benefit from weave.

Mark

**Comment by awh** [comment]
Duplicate of #68.
