### ISSUE TITLE
[dns] facilitate configuration of weavedns docker args

### ISSUE THREAD

**Issue by awh** [zettio/weave#487]
This will provide `weave launch-dns` with analogous behaviour to `weave launch`; the DNS specific `-fallback` option can then be retired.

**Comment by richtera** [comment]
I put a note into #484, but just so it doesn't get lost.
If you re-configure docker -d to use --dns to point to weave-dns so that docker run automatically selects this dns for new dockers, then it would be hard to make the generic mech work if it relied on /etc/resolv.conf. Not impossible, but hard.

**Comment by rade** [comment]
@richtera why do you think this would be hard? Should simply be a matter of WEAVEDNS_DOCKER_ARGS="--dns=FallBackDNSIP".

**Comment by richtera** [comment]
That's a great idea as long as there was a NON_WEAVEDNS_DOCKER_ARGS="--dns=weavednsIP --fixed-cidr=cidr" Maybe there could be a plugin in docker to automatically add the machine to DNS without requiring the weave run command?

The one thing that I am not sure how to reconcile is the fact that weave is an extra feature to docker; so when I want to deploy my marathon group on top of mesos using docker I'd have to specify: "Oh by the way make sure all your dockers are routed correctly using weave and weave-dns." But I know that's silly to expect at this point, but it does seems to be something we need to get beyond.

**Comment by rade** [comment]
> That's a great idea as long as there was a NON_WEAVEDNS_DOCKER_ARGS="--dns=weavednsIP --fixed-cidr=cidr" Maybe there could be a plugin in docker to automatically add the machine to DNS without requiring the weave run command?

Are you asking for a way to run containers and attach them to the weave network and name them in weaveDNS with just plain `docker run` instead of `weave run`? That would be a completely [separate issue](https://github.com/zettio/weave/issues/230).

**Comment by richtera** [comment]
That would be great, but my statement was supposed to be more general thought: There are many different ways to build networks of dockers running across a cluster of machines; I believe this kind of network topology is much easier to manage than random port mappings.

But unless it's build into "most" of the clouds available for people to deploy application the application design kind of bleeds into the infrastructure requirements in weird ways.

I agree it's a completely separate issue, this got me thinking though :).
