### ISSUE TITLE
create-bridge will not work if docker is not running

### ISSUE THREAD

**Issue by kesavkolla** [zettio/weave#492]
I've a setup such a way that I have replace docker0 with weave network.  To achieve this I first do weave create-bridge and assign a cidr then start the docker with options --bridge=weave and --fixed-cidr=<pre-assigned cidr>

With the latest changes this setup is failing.  weave create-bridge is looking for docker up and running.  So entire setup is broken.  Can you make sure create-bridge don't have dependency on docker being running?

Or is there any other solution to make docker to use weave bridge instead of docker0 bridge.

**Comment by rade** [comment]
use `--local`, that's what it is there for. Apologies for breaking your existing setup.
